### ISSUE TITLE
No need to build from source

### ISSUE THREAD

**Issue by achillesliu** [spyder-ide/mac-application#1]
I just used dmg of 2.3.5 on OS X 10.10.3 and found that you just change the python interpreter and all is done! I use homebrew to install python 2.7.10 .

Thanks for the great spyder! Still nothing can be used as an alternative, as least for me.

**Comment by ccordoba12** [comment]
Thanks for the kind words! :-) We work hard to provide the best possible scientific IDE ;-)

The instructions in this repo are necessary to _build_ the dmg, not to _use_ it. After installing our dmg, you can use it with Homebrew, Anaconda, Canopy, etc.

**Comment by achillesliu** [comment]
OK. It seems that I didn't get the point : )

**Comment by ccordoba12** [comment]
No problem :-)
